language: java
sudo: false
install: true
services: cassandra
jdk:
  - oraclejdk8

before_install:
- eval "java -version"
- eval "cqlsh --version"

script:
  - mvn clean package
cache:
  directories:
    - '$HOME/.m2/repository'