language: java
sudo: false
install: true
services: cassandra
jdk:
  - oraclejdk8

before_install:
  - eval "java -version"
  - eval "cqlsh --version"
  - ls -1a
  - cp src/test/resources/application.properties application.properties
  - cp src/test/resources/db-cleanup.cql db-cleanup.cql
  - cp src/test/resources/db-prep.cql db-prep.cql
  - eval "cqlsh -f db-prep.cql"

after_script:
  - eval "cqlsh -f db-cleanup.cql"

script:
  - mvn clean package
cache:
  directories:
    - '$HOME/.m2/repository'